//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivityID { get; set; }
        public int ActivityCategoryID { get; set; }
        public System.DateTime ActivityDate { get; set; }
        public int PersonID { get; set; }
        public int SecondaryPersonID { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual ActivityCategory ActivityCategory { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
