//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public int PersonID { get; set; }
        public int StoryID { get; set; }
        public string Text { get; set; }
        public System.DateTime CommentDate { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Story Story { get; set; }
    }
}
