//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountPerson
    {
        public int PersonID { get; set; }
        public int Comment { get; set; }
        public int Device { get; set; }
        public int Feedback { get; set; }
        public int Follower { get; set; }
        public int Following { get; set; }
        public int LastActivityDate { get; set; }
        public int LikeCount { get; set; }
        public int Login { get; set; }
        public int Moment { get; set; }
        public int ProfileUpdate { get; set; }
        public int Report { get; set; }
        public int ReportedStoryHas { get; set; }
        public int ReTell { get; set; }
        public int Search { get; set; }
        public int Story { get; set; }
        public int StoryCategoryUsed { get; set; }
        public int ThemeUsed { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
