//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceOS
    {
        public DeviceOS()
        {
            this.Device = new HashSet<Device>();
        }
    
        public int OSID { get; set; }
        public string OSName { get; set; }
    
        public virtual ICollection<Device> Device { get; set; }
    }
}
