//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int AppVersionID { get; set; }
        public System.DateTime DateLastLogin { get; set; }
        public System.DateTime DateLogin { get; set; }
        public int DeviceLanguageID { get; set; }
        public int DeviceOsID { get; set; }
        public string DeviceToken { get; set; }
        public int DeviceTypeID { get; set; }
        public bool IsActive { get; set; }
        public int OsVersionID { get; set; }
        public int PersonID { get; set; }
        public int DeviceID { get; set; }
    
        public virtual AppVersion AppVersion { get; set; }
        public virtual Language Language { get; set; }
        public virtual DeviceOs DeviceOs { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual OsVersion OsVersion { get; set; }
        public virtual Person Person { get; set; }
    }
}
