//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public int PersonID { get; set; }
        public System.DateTime SentDate { get; set; }
        public int FeedbackCategoryID { get; set; }
        public string Text { get; set; }
        public bool IsRead { get; set; }
        public bool IsReplied { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual FeedbackCategory FeedbackCategory { get; set; }
    }
}
