//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MomenticEntities : DbContext
    {
        public MomenticEntities()
            : base("name=MomenticEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<ActivityCategory> ActivityCategory { get; set; }
        public virtual DbSet<AppVersion> AppVersion { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<CountMoment> CountMoment { get; set; }
        public virtual DbSet<CountPerson> CountPerson { get; set; }
        public virtual DbSet<CountStory> CountStory { get; set; }
        public virtual DbSet<DeviceOs> DeviceOs { get; set; }
        public virtual DbSet<DeviceType> DeviceType { get; set; }
        public virtual DbSet<Feedback> Feedback { get; set; }
        public virtual DbSet<FeedbackCategory> FeedbackCategory { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Moment> Moment { get; set; }
        public virtual DbSet<MomentLike> MomentLike { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<NotificationCase> NotificationCase { get; set; }
        public virtual DbSet<NotificationType> NotificationType { get; set; }
        public virtual DbSet<OsVersion> OsVersion { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<PersonFollowing> PersonFollowing { get; set; }
        public virtual DbSet<PersonRole> PersonRole { get; set; }
        public virtual DbSet<PersonToken> PersonToken { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<ReTell> ReTell { get; set; }
        public virtual DbSet<SearchHistory> SearchHistory { get; set; }
        public virtual DbSet<Story> Story { get; set; }
        public virtual DbSet<StoryCategory> StoryCategory { get; set; }
        public virtual DbSet<Theme> Theme { get; set; }
        public virtual DbSet<Timeline> Timeline { get; set; }
        public virtual DbSet<Device> Device { get; set; }
    }
}
