//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moment
    {
        public Moment()
        {
            this.MomentLike = new HashSet<MomentLike>();
            this.Story = new HashSet<Story>();
            this.Story1 = new HashSet<Story>();
            this.Story2 = new HashSet<Story>();
            this.Story3 = new HashSet<Story>();
            this.Story4 = new HashSet<Story>();
            this.Story5 = new HashSet<Story>();
            this.Story6 = new HashSet<Story>();
        }
    
        public int MomentID { get; set; }
        public string PhotoUrlActivity { get; set; }
        public string PhotoUrlExplore { get; set; }
        public string PhotoUrlLarge { get; set; }
        public string PhotoUrlOriginal { get; set; }
        public int PersonID { get; set; }
        public string Title { get; set; }
        public string Tag { get; set; }
        public System.DateTime UploadDate { get; set; }
        public bool IsSafe { get; set; }
        public bool IsHorizontal { get; set; }
        public string LocationString { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual ICollection<MomentLike> MomentLike { get; set; }
        public virtual ICollection<Story> Story { get; set; }
        public virtual ICollection<Story> Story1 { get; set; }
        public virtual ICollection<Story> Story2 { get; set; }
        public virtual ICollection<Story> Story3 { get; set; }
        public virtual ICollection<Story> Story4 { get; set; }
        public virtual ICollection<Story> Story5 { get; set; }
        public virtual ICollection<Story> Story6 { get; set; }
    }
}
