//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCase
    {
        public NotificationCase()
        {
            this.Notification = new HashSet<Notification>();
        }
    
        public int NotificationCaseID { get; set; }
        public string NotificationCaseName { get; set; }
    
        public virtual ICollection<Notification> Notification { get; set; }
    }
}
