//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRole
    {
        public PersonRole()
        {
            this.Person = new HashSet<Person>();
        }
    
        public int PersonRoleID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<Person> Person { get; set; }
    }
}
