//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MomenticAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public Theme()
        {
            this.Story = new HashSet<Story>();
            this.Timeline = new HashSet<Timeline>();
            this.Person = new HashSet<Person>();
        }
    
        public int ThemeID { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<Story> Story { get; set; }
        public virtual ICollection<Timeline> Timeline { get; set; }
        public virtual ICollection<Person> Person { get; set; }
    }
}
